export enum ImagenCarta {
    // Corazones
    CorazonesAs = "./assets/assets-blackjack/A-corazon.png",
    Corazones2 = "./assets/assets-blackjack/2-corazon.png",
    Corazones3 = "./assets/assets-blackjack/3-corazon.png",
    Corazones4 = "./assets/assets-blackjack/4-corazon.png",
    Corazones5 = "./assets/assets-blackjack/5-corazon.png",
    Corazones6 = "./assets/assets-blackjack/6-corazon.png",
    Corazones7 = "./assets/assets-blackjack/7-corazon.png",
    Corazones8 = "./assets/assets-blackjack/8-corazon.png",
    Corazones9 = "./assets/assets-blackjack/9-corazon.png",
    Corazones10 = "./assets/assets-blackjack/10-corazon.png",
    CorazonesJ = "./assets/assets-blackjack/J-corazon.png",
    CorazonesQ = "./assets/assets-blackjack/Q-corazon.png",
    CorazonesK = "./assets/assets-blackjack/K-corazon.png",
  
    // Diamantes
    DiamantesAs = "./assets/assets-blackjack/A-diamante.png",
    Diamantes2 = "./assets/assets-blackjack/2-diamante.png",
    Diamantes3 = "./assets/assets-blackjack/3-diamante.png",
    Diamantes4 = "./assets/assets-blackjack/4-diamante.png",
    Diamantes5 = "./assets/assets-blackjack/5-diamante.png",
    Diamantes6 = "./assets/assets-blackjack/6-diamante.png",
    Diamantes7 = "./assets/assets-blackjack/7-diamante.png",
    Diamantes8 = "./assets/assets-blackjack/8-diamante.png",
    Diamantes9 = "./assets/assets-blackjack/9-diamante.png",
    Diamantes10 = "./assets/assets-blackjack/10-diamante.png",
    DiamantesJ = "./assets/assets-blackjack/J-diamante.png",
    DiamantesQ = "./assets/assets-blackjack/Q-diamante.png",
    DiamantesK = "./assets/assets-blackjack/K-diamante.png",
  
    // Tréboles
    TrebolesAs = "./assets/assets-blackjack/A-trebol.png",
    Treboles2 = "./assets/assets-blackjack/2-trebol.png",
    Treboles3 = "./assets/assets-blackjack/3-trebol.png",
    Treboles4 = "./assets/assets-blackjack/4-trebol.png",
    Treboles5 = "./assets/assets-blackjack/5-trebol.png",
    Treboles6 = "./assets/assets-blackjack/6-trebol.png",
    Treboles7 = "./assets/assets-blackjack/7-trebol.png",
    Treboles8 = "./assets/assets-blackjack/8-trebol.png",
    Treboles9 = "./assets/assets-blackjack/9-trebol.png",
    Treboles10 = "./assets/assets-blackjack/10-trebol.png",
    TrebolesJ = "./assets/assets-blackjack/J-trebol.png",
    TrebolesQ = "./assets/assets-blackjack/Q-trebol.png",
    TrebolesK = "./assets/assets-blackjack/K-trebol.png",
  
    // Picas
    PicasAs = "./assets/assets-blackjack/A-picas.png",
    Picas2 = "./assets/assets-blackjack/2-picas.png",
    Picas3 = "./assets/assets-blackjack/3-picas.png",
    Picas4 = "./assets/assets-blackjack/4-picas.png",
    Picas5 = "./assets/assets-blackjack/5-picas.png",
    Picas6 = "./assets/assets-blackjack/6-picas.png",
    Picas7 = "./assets/assets-blackjack/7-picas.png",
    Picas8 = "./assets/assets-blackjack/8-picas.png",
    Picas9 = "./assets/assets-blackjack/9-picas.png",
    Picas10 = "./assets/assets-blackjack/10-picas.png",
    PicasJ = "./assets/assets-blackjack/J-picas.png",
    PicasQ = "./assets/assets-blackjack/Q-picas.png",
    PicasK = "./assets/assets-blackjack/K-picas.png"
  }