export enum Especie {
    Humano = "Humano",
    Magicamente_Alterado = "Mágicamente alterado",
    Quimicamente_Alterado = "Quimicamente Alterado",
    Nacido_con_magia = "Nacido con magia",
    Espiritualista = "Espiritualista",
    Ciborg = "Cíborg",
    Minotauro = "Minotauro",
    Gato = "Gato",
    Darkin = "Darkin",
    Vastaya = "Vastaya",
    Dios = "Dios",
    Dios_Guerrero = "Dios-Guerrero",
    Yeti = "Yeti",
    Demonio = "Demonio",
    Desconocido = "Desconocido",
    Yordle = "Yordle",
    Ser_del_Vacio = "Ser del Vacío",
    Rata = "Rata",
    Nacido_del_Hielo = "Nacido del Hielo",
    Trol = "Trol",
    No_muerto = "No muerto",
    Aspecto = "Aspecto",
    Golem = "Gólem",
    Renacido = "Renacido",
    Espiritu = "Espíritu",
    Brackern = "Brackern",
    Celestial = "Celestial",
    Perro = "Perro",
    Dragon = "Dragón",
}

export type EspecieCollection = Especie[];
